### ISSUE TITLE
Problem with Windows

### ISSUE THREAD

**Issue by hdid** [kpdyer/fteproxy#120]
I installed Windows version (TBB 3.6beta2 + fteproxy 0.2.6) but when i execute fteproxy.exe, it gives this output and exits:
"Traceback (most recent call last):
  File "fteproxy", line 34, in <module>
  File "fte__init__.pyc", line 24, in <module>
  File "fte\encoder.pyc", line 24, in <module>
  File "fte\dfa.pyc", line 24, in <module>
  File "fte\cDFA.pyc", line 12, in <module>
  File "fte\cDFA.pyc", line 10, in __load
ImportError: DLL load failed: The specified module could not be found."

I also installed "Microsoft Visual C++ 2008 Redistributable Package" but didn't help

**Comment by sergeevabc** [comment]
Any place to get working `fteproxy.exe` without Python-specific errors?
I checked Tor Browser Bundle, but it contains none.

**Comment by kpdyer** [comment]
https://fteproxy.org/dist/0.2.18/fteproxy-0.2.18-windows-i386.zip
